services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tyba
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./data:/app/data
    ports:
      - "8088:8088"
    restart: always
    env_file:
      - path: .env
        required: false
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-db-volume:

